# Generated by Django 4.1.4 on 2023-02-07 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Domain', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('Company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core2.company')),
            ],
        ),
    ]
